# Generated by Django 5.0.6 on 2024-08-14 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Kategoriya nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Til',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_1', models.CharField(blank=True, max_length=250, null=True, verbose_name='1-video')),
                ('video_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='2-video')),
                ('video_3', models.CharField(blank=True, max_length=250, null=True, verbose_name='3-video')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': '2. Asosiy videolar',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm 1')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm 2')),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm 3')),
                ('img_4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm 4')),
                ('img_5', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm 5')),
                ('img_6', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm 6')),
                ('img_7', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm 7')),
                ('img_8', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm 8')),
                ('img_9', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm 9')),
                ('view', models.IntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnpz.language')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': '6. Galereya',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnpz.language')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': '5. Savol&Javob',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Sarlavha')),
                ('mainImage', models.ImageField(blank=True, default='new.png', null=True, upload_to='', verbose_name='Asosiy rasm. 500x500 shart')),
                ('description_1', models.TextField(blank=True, null=True, verbose_name="Ta'rif 1")),
                ('description_2', models.TextField(blank=True, null=True, verbose_name="Ta'rif 2")),
                ('description_3', models.TextField(blank=True, null=True, verbose_name="Ta'rif 3")),
                ('description_4', models.TextField(blank=True, null=True, verbose_name="Ta'rif 4")),
                ('description_5', models.TextField(blank=True, null=True, verbose_name="Ta'rif 5")),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm 1')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm 2')),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm 3')),
                ('img_4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm 4')),
                ('img_5', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm 5')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('view', models.IntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnpz.language')),
            ],
            options={
                'verbose_name': 'New',
                'verbose_name_plural': '1. Yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('image', models.ImageField(upload_to='', verbose_name='Asosiy rasm, 500x500 shart')),
                ('advantage', models.TextField(blank=True, null=True, verbose_name='Afzalligi')),
                ('field', models.TextField(blank=True, null=True, verbose_name="Qo'llash sohasi")),
                ('marka', models.CharField(blank=True, max_length=250, null=True, verbose_name='Marka')),
                ('document', models.CharField(blank=True, max_length=250, null=True, verbose_name='Normativ hujjat')),
                ('world_standart', models.CharField(blank=True, max_length=250, null=True, verbose_name="jahon me'yorlariga mosligi")),
                ('used', models.CharField(blank=True, max_length=350, null=True, verbose_name='Istemolchi')),
                ('date', models.CharField(blank=True, max_length=150, null=True, verbose_name="O'zlashtirish sanasi")),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnpz.language')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': '3. Maxsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.IntegerField(default=1)),
                ('service', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('condition', models.TextField(blank=True, null=True, verbose_name='Maxsus shart')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='File')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('term', models.DateField(verbose_name='Ohirgi muddat')),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
                ('view', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnpz.categorytender')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnpz.language')),
            ],
            options={
                'verbose_name': 'Selection',
                'verbose_name_plural': '4. Tanlovlar',
            },
        ),
    ]
