# Generated by Django 5.0.6 on 2024-08-14 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytender',
            options={'verbose_name': 'CategoryTender', 'verbose_name_plural': '4. Tanlovlar kategoyasi'},
        ),
        migrations.AlterModelOptions(
            name='selection',
            options={'verbose_name': 'Selection', 'verbose_name_plural': '4.1 Tanlovlar'},
        ),
    ]
