# Generated by Django 5.0.6 on 2024-08-14 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0002_alter_categorytender_options_alter_selection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnpz.categorytender', verbose_name='Tanlov kategoriyasi'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnpz.language', verbose_name='Tilni tanlang'),
        ),
    ]
