# Generated by Django 5.0.6 on 2024-08-14 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0003_alter_selection_category_alter_selection_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Kategoriya nomi')),
            ],
            options={
                'verbose_name': 'CategoryNew',
                'verbose_name_plural': '1. Yangiliklar kategoyasi',
            },
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'New', 'verbose_name_plural': '1.1 Yangiliklar'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnpz.language', verbose_name='Tilni tanlang'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnpz.language', verbose_name='Tilni tanlang'),
        ),
        migrations.AlterField(
            model_name='new',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnpz.language', verbose_name='Tilni tanlang'),
        ),
        migrations.AlterField(
            model_name='product',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnpz.language', verbose_name='Tilni tanlang'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Telefon raqam'),
        ),
        migrations.AddField(
            model_name='new',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bnpz.categorynew', verbose_name='Kategoriyani tanlang'),
            preserve_default=False,
        ),
    ]
