# Generated by Django 5.0.6 on 2024-08-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0004_categorynew_alter_new_options_alter_faq_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
