# Generated by Django 5.0.6 on 2024-08-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0007_alter_new_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='display_id',
        ),
    ]
