# Generated by Django 5.0.6 on 2024-08-14 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0008_remove_selection_display_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Maxsulot nomi')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Техническая задача (.pdf)')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnpz.language', verbose_name='Tilni tanlang')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnpz.selection', verbose_name='Tanlovning nomi.')),
            ],
            options={
                'verbose_name': 'SelectionProduct',
                'verbose_name_plural': '4.2 Tanlov maxsuloti',
            },
        ),
    ]
