# Generated by Django 5.0.6 on 2024-08-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0009_selectionproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='file',
        ),
    ]
