# Generated by Django 5.0.6 on 2024-08-14 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0010_remove_selection_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectionproduct',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='selectionproduct',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnpz.selection', verbose_name='Tanlovning nomi'),
        ),
    ]
