# Generated by Django 5.0.6 on 2024-08-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0011_selectionproduct_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Qo`llanma'),
        ),
    ]
