# Generated by Django 5.0.6 on 2024-08-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0012_faq_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectionproduct',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktiv'),
        ),
    ]
