# Generated by Django 5.1 on 2024-08-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0013_selectionproduct_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='Ism')),
                ('lastName', models.CharField(max_length=50, verbose_name='Familiya')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('bthDate', models.CharField(max_length=50, verbose_name="Tug'ilgan yili")),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqam')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
                ('theme', models.TextField(verbose_name='Murojaat mavzu')),
                ('text', models.TextField(verbose_name='Murojaat matni')),
                ('date', models.DateField(auto_now_add=True)),
                ('cause', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name="Ko'rib chiqildi")),
            ],
        ),
    ]
