# Generated by Django 5.0.6 on 2024-08-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0014_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message', 'verbose_name_plural': '7. Murojaatlar'},
        ),
        migrations.AlterField(
            model_name='message',
            name='cause',
            field=models.TextField(blank=True, null=True, verbose_name='Murojaatga javob'),
        ),
    ]
