# Generated by Django 5.0.6 on 2024-08-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0015_alter_message_options_alter_message_cause'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'main_sms_code',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
