# Generated by Django 5.0.6 on 2024-08-16 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0016_smscode_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='EskizToken',
        ),
    ]
