# Generated by Django 5.0.6 on 2024-08-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0018_delete_eskiztoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eskiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
