# Generated by Django 5.0.6 on 2024-08-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0019_eskiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Murojaat natijasi fayl shaklida'),
        ),
    ]
