# Generated by Django 5.0.6 on 2024-08-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0020_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscode',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='smscode',
            name='dispatch_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
