# Generated by Django 5.0.6 on 2024-08-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0021_smscode_code_smscode_dispatch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smscode',
            name='dispatch_id',
        ),
    ]
