# Generated by Django 5.0.6 on 2024-08-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0022_remove_smscode_dispatch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sayt nomi')),
                ('img', models.ImageField(upload_to='', verbose_name='Sayt logosi (.png shart)')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Foydali saytlar',
            },
        ),
    ]
