# Generated by Django 5.0.6 on 2024-08-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0023_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Site', 'verbose_name_plural': '8. Foydali saytlar'},
        ),
        migrations.AddField(
            model_name='site',
            name='link',
            field=models.TextField(default=1, verbose_name='Veb sayt linki'),
            preserve_default=False,
        ),
    ]
