# Generated by Django 5.0.6 on 2024-08-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0024_alter_site_options_site_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Hajm')),
                ('subtitle', models.TextField(verbose_name='Nomi')),
                ('img', models.ImageField(upload_to='', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': '8. Statistika',
            },
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Site', 'verbose_name_plural': '9. Foydali saytlar'},
        ),
    ]
