# Generated by Django 5.0.6 on 2024-08-23 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0029_categorynew_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('subtitle', models.TextField(verbose_name="Ta'rif")),
                ('img', models.ImageField(upload_to='', verbose_name='Rasm')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnpz.language', verbose_name='Tilni tanlang')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': '10. Sertifikat',
            },
        ),
    ]
