# Generated by Django 5.0.6 on 2024-08-26 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0030_certificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Site', 'verbose_name_plural': '9.1. Sertifikat'},
        ),
    ]
