# Generated by Django 5.0.6 on 2024-08-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0031_alter_certificate_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorynew',
            name='language',
        ),
        migrations.RemoveField(
            model_name='categorynew',
            name='title',
        ),
        migrations.AddField(
            model_name='categorynew',
            name='title_en',
            field=models.CharField(default=1, max_length=500, verbose_name='Kategoriya nomi (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorynew',
            name='title_kr',
            field=models.CharField(default=1, max_length=500, verbose_name='Kategoriya nomi (Крилл)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorynew',
            name='title_ru',
            field=models.CharField(default=1, max_length=500, verbose_name='Kategoriya nomi (Русский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorynew',
            name='title_uz',
            field=models.CharField(default=1, max_length=500, verbose_name='Kategoriya nomi (Uzbek)'),
            preserve_default=False,
        ),
    ]
