# Generated by Django 5.0.6 on 2024-08-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0032_remove_categorynew_language_remove_categorynew_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorynew',
            name='en',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='categorynew',
            name='kr',
            field=models.CharField(default='kr', max_length=10),
        ),
        migrations.AddField(
            model_name='categorynew',
            name='ru',
            field=models.CharField(default='ru', max_length=10),
        ),
        migrations.AddField(
            model_name='categorynew',
            name='uz',
            field=models.CharField(default='uz', max_length=10),
        ),
    ]
