# Generated by Django 5.0.6 on 2024-08-26 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0033_categorynew_en_categorynew_kr_categorynew_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new', to='bnpz.categorynew', verbose_name='Kategoriyani tanlang'),
        ),
    ]
