# Generated by Django 5.0.6 on 2024-08-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0034_alter_new_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Nomer: '),
            preserve_default=False,
        ),
    ]
