# Generated by Django 5.0.6 on 2024-08-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0035_new_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytender',
            options={'verbose_name': 'CategoryNew', 'verbose_name_plural': '1. Yangiliklar kategoyasi'},
        ),
        migrations.RemoveField(
            model_name='categorytender',
            name='language',
        ),
        migrations.RemoveField(
            model_name='categorytender',
            name='title',
        ),
        migrations.AddField(
            model_name='categorytender',
            name='en',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='categorytender',
            name='kr',
            field=models.CharField(default='kr', max_length=10),
        ),
        migrations.AddField(
            model_name='categorytender',
            name='ru',
            field=models.CharField(default='ru', max_length=10),
        ),
        migrations.AddField(
            model_name='categorytender',
            name='title_en',
            field=models.CharField(default=1, max_length=500, verbose_name='Kategoriya nomi (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorytender',
            name='title_kr',
            field=models.CharField(default=1, max_length=500, verbose_name='Kategoriya nomi (Крилл)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorytender',
            name='title_ru',
            field=models.CharField(default=1, max_length=500, verbose_name='Kategoriya nomi (Русский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorytender',
            name='title_uz',
            field=models.CharField(default=1, max_length=500, verbose_name='Kategoriya nomi (Uzbek)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorytender',
            name='uz',
            field=models.CharField(default='uz', max_length=10),
        ),
    ]
