# Generated by Django 5.0.6 on 2024-08-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0036_alter_categorytender_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytender',
            options={'verbose_name': 'CategoryTender', 'verbose_name_plural': '4. Tanlov kategoyasi'},
        ),
        migrations.AddField(
            model_name='selection',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Nomer: '),
            preserve_default=False,
        ),
    ]
