# Generated by Django 5.0.6 on 2024-08-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0039_localdocs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=500, verbose_name='Lavozimi')),
                ('firstName', models.CharField(max_length=500, verbose_name='Ism')),
                ('lastName', models.CharField(max_length=500, verbose_name='Familiya')),
                ('sureName', models.CharField(max_length=500, verbose_name='Otasining ismi')),
                ('phone', models.CharField(max_length=500, verbose_name='Telefon raqami')),
                ('acceptance', models.TextField(verbose_name='Qabul kunlari')),
                ('experience_1', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mehnat faoliyati 1')),
                ('experience_2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mehnat faoliyati 2')),
                ('experience_3', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mehnat faoliyati 3')),
                ('experience_4', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mehnat faoliyati 4')),
                ('experience_5', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mehnat faoliyati 5')),
                ('experience_6', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mehnat faoliyati 6')),
                ('experience_7', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mehnat faoliyati 7')),
                ('experience_8', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mehnat faoliyati 8')),
                ('experience_9', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mehnat faoliyati 9')),
                ('experience_10', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mehnat faoliyati 10')),
                ('experience_11', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mehnat faoliyati 11')),
                ('experience_12', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mehnat faoliyati 12')),
                ('experience_13', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mehnat faoliyati 13')),
                ('experience_14', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mehnat faoliyati 14')),
                ('experience_15', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mehnat faoliyati 15')),
                ('functional_1', models.CharField(blank=True, max_length=500, null=True, verbose_name='Funksional majburiyati 1')),
                ('functional_2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Funksional majburiyati 2')),
                ('functional_3', models.CharField(blank=True, max_length=500, null=True, verbose_name='Funksional majburiyati 3')),
                ('functional_4', models.CharField(blank=True, max_length=500, null=True, verbose_name='Funksional majburiyati 4')),
                ('functional_5', models.CharField(blank=True, max_length=500, null=True, verbose_name='Funksional majburiyati 5')),
                ('functional_6', models.CharField(blank=True, max_length=500, null=True, verbose_name='Funksional majburiyati 6')),
                ('functional_7', models.CharField(blank=True, max_length=500, null=True, verbose_name='Funksional majburiyati 7')),
                ('functional_8', models.CharField(blank=True, max_length=500, null=True, verbose_name='Funksional majburiyati 8')),
                ('functional_9', models.CharField(blank=True, max_length=500, null=True, verbose_name='Funksional majburiyati 9')),
                ('functional_10', models.CharField(blank=True, max_length=500, null=True, verbose_name='Funksional majburiyati 10')),
            ],
            options={
                'verbose_name': 'Lider',
                'verbose_name_plural': '9.3. Rahbariyat',
            },
        ),
        migrations.AlterModelOptions(
            name='localdocs',
            options={'verbose_name': 'LocalDocs', 'verbose_name_plural': "9.2. Lokal me'yoriy hujjatlar"},
        ),
    ]
