# Generated by Django 5.0.6 on 2024-08-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0041_lider_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='lider',
            name='img',
            field=models.ImageField(default=1, upload_to='', verbose_name='Rasm'),
            preserve_default=False,
        ),
    ]
