# Generated by Django 5.0.6 on 2024-08-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0043_lider_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Nomer'),
            preserve_default=False,
        ),
    ]
