# Generated by Django 5.0.6 on 2024-08-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0044_certificate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='description_1',
            field=models.TextField(blank=True, null=True, verbose_name='Matn 1'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='description_2',
            field=models.TextField(blank=True, null=True, verbose_name='Matn 2'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='description_3',
            field=models.TextField(blank=True, null=True, verbose_name='Matn 3'),
        ),
    ]
