# Generated by Django 5.0.6 on 2024-09-01 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0045_certificate_description_1_certificate_description_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Certificate', 'verbose_name_plural': '9.1. Sertifikat'},
        ),
    ]
