# Generated by Django 5.0.6 on 2024-09-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0047_product_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Nomer'),
            preserve_default=False,
        ),
    ]
