# Generated by Django 5.0.6 on 2024-09-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0049_captcha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
    ]
