# Generated by Django 5.0.6 on 2024-09-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0051_alter_product_options_productnew'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productnew',
            options={'verbose_name': 'ProductNew', 'verbose_name_plural': '3. Maxsulotlar'},
        ),
        migrations.AddField(
            model_name='productnew',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Nomer'),
            preserve_default=False,
        ),
    ]
