# Generated by Django 5.0.6 on 2024-09-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0052_alter_productnew_options_productnew_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='advantage',
            new_name='advantage1',
        ),
    ]
