# Generated by Django 5.0.6 on 2024-09-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0053_rename_advantage_product_advantage1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='advantage_2',
            field=models.TextField(blank=True, null=True, verbose_name='Afzalligi 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='advantage_3',
            field=models.TextField(blank=True, null=True, verbose_name='Afzalligi 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='advantage_4',
            field=models.TextField(blank=True, null=True, verbose_name='Afzalligi 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='advantage_5',
            field=models.TextField(blank=True, null=True, verbose_name='Afzalligi 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='advantage_6',
            field=models.TextField(blank=True, null=True, verbose_name='Afzalligi 6'),
        ),
        migrations.AddField(
            model_name='product',
            name='advantage_7',
            field=models.TextField(blank=True, null=True, verbose_name='Afzalligi 7'),
        ),
        migrations.AddField(
            model_name='product',
            name='advantage_8',
            field=models.TextField(blank=True, null=True, verbose_name='Afzalligi 8'),
        ),
        migrations.AddField(
            model_name='product',
            name='date_2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="O'zlashtirish sanasi 2"),
        ),
        migrations.AddField(
            model_name='product',
            name='date_3',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="O'zlashtirish sanasi 3"),
        ),
        migrations.AddField(
            model_name='product',
            name='date_4',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="O'zlashtirish sanasi 4"),
        ),
        migrations.AddField(
            model_name='product',
            name='date_5',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="O'zlashtirish sanasi 5"),
        ),
        migrations.AddField(
            model_name='product',
            name='date_6',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="O'zlashtirish sanasi 6"),
        ),
        migrations.AddField(
            model_name='product',
            name='date_7',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="O'zlashtirish sanasi 7"),
        ),
        migrations.AddField(
            model_name='product',
            name='date_8',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="O'zlashtirish sanasi 8"),
        ),
        migrations.AddField(
            model_name='product',
            name='document_2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Normativ hujjat 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='document_3',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Normativ hujjat 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='document_4',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Normativ hujjat 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='document_5',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Normativ hujjat 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='document_6',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Normativ hujjat 6'),
        ),
        migrations.AddField(
            model_name='product',
            name='document_7',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Normativ hujjat 7'),
        ),
        migrations.AddField(
            model_name='product',
            name='document_8',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Normativ hujjat 8'),
        ),
        migrations.AddField(
            model_name='product',
            name='field_2',
            field=models.TextField(blank=True, null=True, verbose_name="Qo'llash sohasi 2"),
        ),
        migrations.AddField(
            model_name='product',
            name='field_3',
            field=models.TextField(blank=True, null=True, verbose_name="Qo'llash sohasi 3"),
        ),
        migrations.AddField(
            model_name='product',
            name='field_4',
            field=models.TextField(blank=True, null=True, verbose_name="Qo'llash sohasi 4"),
        ),
        migrations.AddField(
            model_name='product',
            name='field_5',
            field=models.TextField(blank=True, null=True, verbose_name="Qo'llash sohasi 5"),
        ),
        migrations.AddField(
            model_name='product',
            name='field_6',
            field=models.TextField(blank=True, null=True, verbose_name="Qo'llash sohasi 6"),
        ),
        migrations.AddField(
            model_name='product',
            name='field_7',
            field=models.TextField(blank=True, null=True, verbose_name="Qo'llash sohasi 7"),
        ),
        migrations.AddField(
            model_name='product',
            name='field_8',
            field=models.TextField(blank=True, null=True, verbose_name="Qo'llash sohasi 8"),
        ),
        migrations.AddField(
            model_name='product',
            name='marka_2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Marka 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='marka_3',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Marka 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='marka_4',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Marka 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='marka_5',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Marka 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='marka_6',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Marka 6'),
        ),
        migrations.AddField(
            model_name='product',
            name='marka_7',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Marka 7'),
        ),
        migrations.AddField(
            model_name='product',
            name='marka_8',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Marka 8'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Maxsulot nomi 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_3',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Maxsulot nomi 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_4',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Maxsulot nomi 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_5',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Maxsulot nomi 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_6',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Maxsulot nomi 6'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_7',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Maxsulot nomi 7'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_8',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Maxsulot nomi 8'),
        ),
        migrations.AddField(
            model_name='product',
            name='used_2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Istemolchi 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='used_3',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Istemolchi 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='used_4',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Istemolchi 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='used_5',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Istemolchi 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='used_6',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Istemolchi 6'),
        ),
        migrations.AddField(
            model_name='product',
            name='used_7',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Istemolchi 7'),
        ),
        migrations.AddField(
            model_name='product',
            name='used_8',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Istemolchi 8'),
        ),
        migrations.AddField(
            model_name='product',
            name='world_standart_2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Jahon me'yorlariga mosligi 2"),
        ),
        migrations.AddField(
            model_name='product',
            name='world_standart_3',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Jahon me'yorlariga mosligi 3"),
        ),
        migrations.AddField(
            model_name='product',
            name='world_standart_4',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Jahon me'yorlariga mosligi 4"),
        ),
        migrations.AddField(
            model_name='product',
            name='world_standart_5',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Jahon me'yorlariga mosligi 5"),
        ),
        migrations.AddField(
            model_name='product',
            name='world_standart_6',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Jahon me'yorlariga mosligi 6"),
        ),
        migrations.AddField(
            model_name='product',
            name='world_standart_7',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Jahon me'yorlariga mosligi 7"),
        ),
        migrations.AddField(
            model_name='product',
            name='world_standart_8',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Jahon me'yorlariga mosligi 8"),
        ),
    ]
