# Generated by Django 5.0.6 on 2024-09-23 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0054_product_advantage_2_product_advantage_3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': '3. Mahsulotlar'},
        ),
    ]
