# Generated by Django 5.0.6 on 2024-09-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0055_alter_product_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductNew',
        ),
    ]
