# Generated by Django 5.0.6 on 2024-09-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0057_alter_new_description_1_alter_new_description_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='description_1',
            field=models.TextField(blank=True, null=True, verbose_name="Ta'rif 1"),
        ),
    ]
