# Generated by Django 5.0.6 on 2024-10-09 10:26

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0060_politica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='politica',
            options={'verbose_name': 'Politica', 'verbose_name_plural': '9.4. Siyosat'},
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Matn')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnpz.language', verbose_name='Til')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': '9.5. Xronika',
            },
        ),
    ]
