# Generated by Django 5.0.6 on 2024-10-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0061_alter_politica_options_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectionproduct',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='selected', verbose_name='Техническая задача (.pdf)'),
        ),
        migrations.AlterField(
            model_name='selectionproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='selectionproduct',
            name='title',
            field=models.TextField(verbose_name='Maxsulot nomi'),
        ),
    ]
