# Generated by Django 5.0.6 on 2024-10-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0063_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
    ]
