# Generated by Django 4.2 on 2024-12-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0065_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm 1')),
            ],
            options={
                'verbose_name': 'Konstitutsiya fotogalereya',
                'verbose_name_plural': '9.6 Konstitutsiya fotogalereya',
            },
        ),
        migrations.CreateModel(
            name='ConsVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, null=True, verbose_name="Youtube link qo'ying")),
            ],
            options={
                'verbose_name': 'Konstitutsiya video',
                'verbose_name_plural': '9.7 Konstitutsiya video',
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
