# Generated by Django 4.2 on 2024-12-02 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0066_consphoto_consvideo_delete_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consphoto',
            options={'verbose_name': 'Konstitutsiya foto', 'verbose_name_plural': '9.6 Konstitutsiya fotogalereya'},
        ),
    ]
