# Generated by Django 4.2 on 2024-12-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0067_alter_consphoto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, null=True, verbose_name='Link uchun joy')),
            ],
            options={
                'verbose_name': 'Konstitutsiya link',
                'verbose_name_plural': '9.6 Konstitutsiya link',
            },
        ),
        migrations.AlterModelOptions(
            name='consphoto',
            options={'verbose_name': 'Konstitutsiya foto', 'verbose_name_plural': '9.7 Konstitutsiya foto'},
        ),
        migrations.AlterModelOptions(
            name='consvideo',
            options={'verbose_name': 'Konstitutsiya video', 'verbose_name_plural': '9.8 Konstitutsiya video'},
        ),
        migrations.AlterField(
            model_name='consphoto',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm'),
        ),
    ]
