# Generated by Django 4.2 on 2024-12-02 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0068_conslink_alter_consphoto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conslink',
            options={'verbose_name': 'Konstitutsiya link', 'verbose_name_plural': '9.7 Konstitutsiya link'},
        ),
        migrations.AlterModelOptions(
            name='consphoto',
            options={'verbose_name': 'Konstitutsiya foto', 'verbose_name_plural': '9.8 Konstitutsiya foto'},
        ),
        migrations.AlterModelOptions(
            name='consvideo',
            options={'verbose_name': 'Konstitutsiya video', 'verbose_name_plural': '9.9 Konstitutsiya video'},
        ),
        migrations.AddField(
            model_name='conslink',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnpz.language', verbose_name='Til'),
        ),
    ]
