# Generated by Django 4.2 on 2024-12-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0069_alter_conslink_options_alter_consphoto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conslink',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Nomer: '),
            preserve_default=False,
        ),
    ]
