# Generated by Django 4.2 on 2024-12-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0071_conslink_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consphoto',
            name='img_1',
            field=models.ImageField(blank=True, default='cons.jpg', null=True, upload_to='', verbose_name='Rasm'),
        ),
    ]
