# Generated by Django 4.2 on 2024-12-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnpz', '0072_alter_consphoto_img_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consphoto',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm'),
        ),
    ]
